### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns

### ISSUE THREAD

**Issue by ProgrammingAtDawn** [bmhm/ExperienceBank3#4]
Chunks are not checked for being loaded. "getChunkAt" causes chunk loading and following exceptions

```
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:39)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:41)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:42)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:43)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:44)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:650)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:45)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:54] [Craft Scheduler Thread - 14/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.MCUtil.ensureMain(MCUtil.java:40)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:149)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getBlockAt(CraftWorld.java:93)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.CraftChunk.getTileEntities(CraftChunk.java:110)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:49)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:13:54] [Craft Scheduler Thread - 14/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:13:56] [Craft Scheduler Thread - 11/WARN]: Exception in thread "Craft Scheduler Thread - 11"
[21:13:56] [Craft Scheduler Thread - 11/WARN]: org.apache.commons.lang.UnhandledException: Plugin ExpBank v3.0.5.0 generated an exception while executing task 2410
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous Async Player Chunk Add!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
    at net.minecraft.server.v1_9_R2.PlayerChunkMap.a(PlayerChunkMap.java:440)
    at net.minecraft.server.v1_9_R2.PlayerChunk.a(PlayerChunk.java:163)
    at net.minecraft.server.v1_9_R2.PlayerChunkMap.flagDirty(PlayerChunkMap.java:270)
    at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:43)
    at net.minecraft.server.v1_9_R2.World.notify(World.java:472)
    at org.bukkit.craftbukkit.v1_9_R2.block.CraftBlockState.update(CraftBlockState.java:166)
    at org.bukkit.craftbukkit.v1_9_R2.block.CraftSign.update(CraftSign.java:52)
    at org.bukkit.craftbukkit.v1_9_R2.block.CraftBlockState.update(CraftBlockState.java:150)
    at org.bukkit.craftbukkit.v1_9_R2.block.CraftBlockState.update(CraftBlockState.java:146)
    at com.empcraft.xpbank.logic.SignHelper.updateSign(SignHelper.java:77)
    at com.empcraft.xpbank.threads.UpdateAllSignsThread.run(UpdateAllSignsThread.java:56)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 4 more
```

**Comment by bmarwell** [comment]
That's a good point. I don't think the original plugin had something like this. Can you file a pull request?
Also, perhaps this might fix my problems with having a modified hashmap which crashes my own server in rare occasions.

**Comment by ProgrammingAtDawn** [comment]
Sorry, there is nothing to pull. I'm not a plugin developer and don't have the setup to test anything well enough.
